### PR TITLE
add scr & sdr, fix mos values

### PR DESCRIPTION
**Pull request by negbie**
Moved performance metrics ratio functions above method counter reset so we can use the counter and reset them later.
Changed some x-rtp-stats variables.

### CODE REVIEW

**Comment by negbie** [comment]
Im still not sure about the Session Completion Ratio (SCR) and what RFC 6076 mean with "Total number of Session Requests". Do they mean dialogs? So is it enough to count the call-id's for new invites? Or should i combine them with to-tag and from-tag in case of call forking? Maybe Federico can shed some light onto it.

**Comment by grumvalski** [comment]
Sorry for the delay, I've finally found the time to have a look at the rfc. According to section 5.4 it looks like forking should be taken in count. It doesn't look easy to implement. Since the rest of the PR looks good, I'd propose to merge it, with the current SCR implementation and then improve this metric. Thanks!

**Comment by negbie** [comment]
Oh im glad you had the time to look at it. Thank you. Sounds good. Maybe its also time to simplify this config a bit? Have a look here: https://github.com/negbie/kam_hom_to_graylog/blob/master/kamailio.cfg

This has more or less the same functionality (ua + si stats and alarm handled by homer are removed)

**Comment by grumvalski** [comment]
Thanks! I'll have a look soon :)

**Comment by negbie** [comment]
Tested on a system with 1500 concurrent calls and works flawlessly

**Comment by lmangani** [comment]
Shall we make a home/repo for all this wonderful stuff?

**Comment by negbie** [comment]
Sounds good but we really need some pieces of docu for it ;)

**Comment by negbie** [comment]
And some shiny pics or even better gifs! Everything is better in a gif :dancing_women:

**Comment by grumvalski** [comment]
Back from travelling. As discussed I'm going to merge this PR. 
I'll also start looking on how to port this to Homer. I was thinking, as discussed with Lorenzo, to follow a modular approach for the configuration file, splitting it in smaller files. I'll come back with a proposal.

**Pull request merged**
